### ISSUE TITLE
`for` loop cannot always use `let`

### ISSUE THREAD

**Issue by eventualbuddha** [juliankrispel/decaf#104]
This [example](http://tsuchikazu.github.io/decaf/#?evaluate=true&code=for%20a%20in%20%5B1%2C%202%2C%203%5D%0A%20%20a%0Aconsole.log(a)):

```coffee
for a in [1, 2, 3]
  a
console.log(a)
```

Outputs `3` when run with the real CoffeeScript compiler, but produces a reference error when run via decaf + babel. This is decaf's output:

```js
for (let a in [1, 2, 3]) {
  a;
}

console.log(a);
```

Ignoring the fact that it should be `of` and not `in` (#96), if we change it to `of` and run it in [babel's repl](http://babeljs.io/repl/#?experimental=true&evaluate=true&loose=false&spec=false&code=for%20(let%20a%20of%20%5B1%2C%202%2C%203%5D)%20%7B%0A%20%20a%3B%0A%7D%0A%0Aconsole.log(a)%3B), we can see that it changes `a` within the loop to `_a` to prevent collision with what babel assumes to be a global reference to `a` in the `console.log` call.

Since all CoffeeScript variable assignments become `var`, it is tricky to know exactly when it's safe to use block scoping. To address this in decaffeinate, I plan to integrate [esnext](https://github.com/esnext/esnext)'s [block scoping plugin](https://github.com/esnext/esnext/blob/master/src/plugins/declarations.block-scope.js) into the conversion process. [Here's the relevant test for this situation.](https://github.com/esnext/esnext/blob/master/test/form/declarations.block-scope/var-for-in-loop-binding-used-outside/main.js) Decaf could either do the same thing, which would be great since more users of esnext means it's more likely to be robust, or it could duplicate and embed essentially the same logic from the linked plugin.

[Here's the latest release of decaffeinate on the same code.](http://decaffeinate.github.io/decaffeinate/repl/#?evaluate=true&code=for%20a%20in%20%5B1%2C%202%2C%203%5D%0A%20%20a%0Aconsole.log(a))

**Comment by juliankrispel** [comment]
thanks @eventualbuddha
