### ISSUE TITLE
`throw` as the last statement of a function should not be wrapped in an IIFE

### ISSUE THREAD

**Issue by eventualbuddha** [juliankrispel/decaf#113]
[See example](http://www.goodafternoon.co/decaf/#?evaluate=true&code=-%3E%0A%20%20throw%20a):

```coffee
->
  throw a
```

```js
(function() {
  return (() => {
    throw a;
  })();
});
```

Originally from [cake.coffee](https://github.com/jashkenas/coffeescript/blob/88192c197a86759e25e1a0d8a31909b72a96cbc8/src/cake.coffee#L88).

**Comment by juliankrispel** [comment]
thanks @eventualbuddha will fix shortly
