### ISSUE TITLE
Class properties are causing parse error

### ISSUE THREAD

**Issue by carlmathisen** [juliankrispel/decaf#123]
Check it out:

```coffeescript
class Test
  myProperty: 'value'
```

compiles to:
```js
class Test {
  myProperty = "value";
}
```
with the error `Unexpected token =`

http://www.goodafternoon.co/decaf/#?evaluate=true&code=class%20Test%0A%20%20myProperty%3A%20'value' #

**Comment by juliankrispel** [comment]
thanks @carlmathisen that's actually an error thrown by ace editor. I'm guessing it doesn't do es7 class properties. @tsuchikazu could you maybe have a quick look?

**Comment by tsuchikazu** [comment]
decaf compiled correctly. 

Ace editor evaluate compiled JavaScript code directly. [Class Instance Fields](https://github.com/jeffmo/es-class-fields-and-static-properties#part-1-class-instance-fields) syntax is not implemented in all browser yet. Try it page can only compile coffeescript to JavaScript code. Could you compile by babel to evaluate JavaSciprt code?

https://babeljs.io/repl/#?evaluate=false&presets=es2015%2Cstage-1&experimental=false&loose=true&spec=true&code=class%20Test%20{%0A%20%20myProperty%20%3D%20%22value%22%3B%0A}

**Comment by carlmathisen** [comment]
Makes sense. Thanks!
