### ISSUE TITLE
Private statements

### ISSUE THREAD

**Issue by juliankrispel** [juliankrispel/decaf#129]
In coffee-script it's entirely legal to just have random statements inside a class definition.

```cs
class A
  b()
  a + 1
```

This is what the compiler spits out:

```js
var A;

A = (function() {
  function A() {}

  b();

  a + 1;

  return A;

})();
```

The only idea I have for this so far is to also wrap the es6 class in a self-invoked function

**Comment by juliankrispel** [comment]
my attempt at solving this would be to put it inside the constructor, thoughts @eventualbuddha

**Comment by eventualbuddha** [comment]
It's pretty bad, though, because you could do stuff like this:

```coffee
class A
  @set = (key, value) -> @[key] = value
  @set 'log', (message) -> console.log('A says', message)
  @log 'foo'
```

**Comment by juliankrispel** [comment]
@eventualbuddha the feature in itself is pretty bad. I'm thinking about just throwing an error telling the user to fix
