### ISSUE TITLE
Does not support '**' operator

### ISSUE THREAD

**Issue by VilleMiekkoja** [juliankrispel/decaf#138]
Hello,

The decaf module crashes if ** is used instead of pow:

`node_modules\decafjs\node_modules\ast-types\lib\types.js:576
                    throw new Error(
                    ^
Error: "**" does not match field "operator": == | != | === | !== | < | <= | > | >= | << | >> | >>> | + | - | * | / | % | & | | | ^ | in | instanceof | .. of type Bin
aryExpression
  at add (node_modules\decafjs\node_modules\ast-types\lib\types.js:576:27)`

It would be nice to have ** support too.

BR,
Ville Miekk-oja

**Comment by juliankrispel** [comment]
thanks @VilleMiekkoja I'll have a look

**Comment by juliankrispel** [comment]
@VilleMiekkoja done thanks for reporting
