### ISSUE TITLE
Location, location, location.

### ISSUE THREAD

**Issue by jashkenas** [juliankrispel/decaf#14]
Hey Julian & co.

This is a very neat effort, and I wonder if you'd prefer commit access to be able to work on it directly inside of the CoffeeScript repo in a "decaf" branch, instead of as a separate project. If that sounds interesting to you, I bet it'd be interesting to a whole bunch of folks over there.

Let me know. And if I'm not responding to a question on Github (for example, a follow-up comment on this thread), feel free to email me directly. I don't have much time to check the issues at the moment.

**Comment by jdalton** [comment]
:clap:

**Comment by juliankrispel** [comment]
thanks @jashkenas I'll respond via email

**Comment by juliankrispel** [comment]
it is very flattering btw ;)

**Comment by rstacruz** [comment]
for those of us out of loop, what's the status on coffee-script/decaf/coffeescript-redux?

**Comment by juliankrispel** [comment]
@rstacruz [this issue](https://github.com/jashkenas/coffeescript/issues/4078) sums up all discussion we've had so far.

Personally I'm starting to work on a branch of coffeescript which adds es6 as a compile target and I'm working on making decaf better. Decaf is still fairly young so if you want to help try it and see if you find issues :)

**Comment by jcollum** [comment]
@juliankrispel are you interested in help on this? I can devote one day every couple of weeks to it at work, it would be a great use of my time -- there are ES2015 features that I could see being useful

**Comment by GeoffreyBooth** [comment]
@juliankrispel What’s the current status of Decaf?

There’s a [repo](https://github.com/coffeescript6/discuss/) where people have been discussing the future of CoffeeScript, including [adding support for ES2015+ features](https://github.com/coffeescript6/discuss/blob/master/Features.md) and outputting ESNext. Would Decaf be an option for outputting ESNext code from the CoffeeScript compiler? If it’s not there yet, how much effort do you think it would take to get there?
