### ISSUE TITLE
Try to Expression

### ISSUE THREAD

**Issue by also** [juliankrispel/decaf#17]
I expected decaf to fall back to the CoffeeScript compiler here:

```
> decaf.compile('x = try y()');
Error: can't convert node of type: Try to Expression - not recognized
```

From the CoffeeScript compiler:
```javascript
x = (function() {
  try {
    return y();
  } catch (undefined) {}
})();
```

**Comment by juliankrispel** [comment]
thanks I forgot about that one

**Comment by juliankrispel** [comment]
actually I am dealing with try catch blocks but not with try expressions it seems. Will add that shortly and update you.

**Comment by juliankrispel** [comment]
@also sorted. I also (no pun intended) published a new version on npm, thanks for reporting the issue and let me know if you find more :)
