### ISSUE TITLE
Support classes with nested name

### ISSUE THREAD

**Issue by bouk** [juliankrispel/decaf#49]
Hi! Thanks for the amazing work on this.

The following code is valid CoffeeScript:

```coffeescript
class Cool.Neat
```

It results in the following JS

```js
Cool.Neat = (function() {
  function Neat() {}

  return Neat;

})();
```

Currently decafjs throws an error when it finds this:

```
Error: {type: MemberExpression, computed: false, object: [object Object], property: [object Object], loc: [object Object]} does not match field "id": Identifier | null of type ClassDeclaration
```

**Comment by juliankrispel** [comment]
hi thanks I'll have a look asap

**Comment by juliankrispel** [comment]
@bouk fixed that. It'll be included in the next release (probably tomorrow morning)

**Comment by bouk** [comment]
Very nice :+1:
