### ISSUE TITLE
Online transpiler

### ISSUE THREAD

**Issue by juliankrispel** [juliankrispel/decaf#76]
That'd be kind of useful for people to try out decaf.

**Comment by tsuchikazu** [comment]
I tried create online transpiler. How do you like this?
site: http://tsuchikazu.github.io/decaf/
sourcecode: https://github.com/tsuchikazu/decaf/tree/gh-pages
( logo image is temporary...)

I inspired by decaffeinate github pages.
http://decaffeinate.github.io/decaffeinate/repl/

If you create gh-pages branchs, I'll send PR!

**Comment by eventualbuddha** [comment]
> I inspired by decaffeinate github pages.
> http://decaffeinate.github.io/decaffeinate/repl/

Which is, in turn, inspired by http://babeljs.io/repl/ ;)

**Comment by juliankrispel** [comment]
@tsuchikazu AWESOME THANKS!!!. Can you remove the logo I'm in the process of designing one myself. Just text would be fine <3

**Comment by tsuchikazu** [comment]
@eventualbuddha Oh, I see!

@juliankrispel 
I removed logo image(http://tsuchikazu.github.io/decaf/). I'm looking forward to your logo. 

Would you create gh-pages branch on juliankrispel/decaf? 
ref [Creating Project Pages manually - User Documentation](https://help.github.com/articles/creating-project-pages-manually/)

**Comment by juliankrispel** [comment]
@tsuchikazu opened a branch <3
