### ISSUE TITLE
should not return in constructor of class

### ISSUE THREAD

**Issue by tsuchikazu** [juliankrispel/decaf#78]
This is error report. I guess should not return at last statement in constructor of class.
In my coffeescript usecase.

coffeescirpt
```coffeescript
class A
  constructor: ->
    @a = []

console.log Array.isArray(new A()) # false
```

transpiled js
```javascript
class A {
  constructor() {
    return this.a = [];
  }
}

console.log(Array.isArray(new A())); // true!?
```

**Comment by juliankrispel** [comment]
great point thanks @tsuchikazu.

Coffeescript does this as well

**Comment by tsuchikazu** [comment]
Thank you for very quick fixed!!! :smile:

**Comment by juliankrispel** [comment]
@tsuchikazu you're welcome :D 

Thanks for reporting! It's published on npm btw!
