### ISSUE TITLE
No way to correctly translate code that assigns to this in constructor and calls super at the same time

### ISSUE THREAD

**Issue by bouk** [juliankrispel/decaf#98]
This is a tricky one, and I think the best solution might be to just throw an error and tell the user to translate this by hand

```coffeescript
class A extends B
  constructor: (@a, @b) ->
    super
    console.log(@a)

```

Generates

```javascript
class A extends B {
  constructor(a, b) {
    this.a = a;
    this.b = b;
    super(...arguments);
    console.log(this.a);
  }
}
```

Which is invalid, because in es6 you can't reference `this` before `super`

**Comment by eventualbuddha** [comment]
Why not simply put the assignments after the `super` call? Of course, you'd still have problems if the code references `this` before the `super` call. In that case an error is probably appropriate. Or there could be an option to output a `function` instead of a class if you really want to go crazy.

**Comment by bouk** [comment]
You could definitely place the assignments before the super, it's just that it would emit different code and could break things (like if the super constructor depends on those variables being assigned for some weird reason).

Throwing an error would be the safest bet

**Comment by juliankrispel** [comment]
@eventualbuddha @bouk I think throwing an error is the right call here..
